[package]
name = "riscv-rtfm"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]

[dependencies]
riscv = "0.2.0"
riscv-rtfm-macros = { path = "macros" }
rtfm-core = "0.2.0"
untagged-option = "0.1.1"
