[package]
name = "riscv-rtfm"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]

[dependencies]
rtfm-core = "0.2.0"
static-ref = "0.2.1"

[dependencies.riscv]
path = "../riscv"

[dependencies.riscv-rtfm-macros]
path = "./macros"